### ISSUE TITLE
求助帖

### ISSUE THREAD

**Issue by ZIbuyu1200** [hzhao98/GDCL#1]
作者大大好，
请问能提供一下你预训练好的文件吗？
我还想请教一下用MVGRL预训练
谢谢大大Orz

**Comment by yueliu1999** [comment]
Hi, I am interested in your paper “Graph Debiased Contrastive Learning with Joint Representation Clustering”. However, I have the same issue with @ZIbuyu1200 when I run your released code. Could you help us.

**Comment by cathyliuchen** [comment]
Hi, there.  I'm trying to replicate your piece of work GDCL, but finding constant error with such feedback:

RuntimeError: CUDA out of memory. Tried to allocate 5.79 GiB (GPU 1; 7.93 GiB total capacity; 3.10 GiB already allocated; 4.28 GiB free; 3.10 GiB reserved in total by PyTorch)

I've tried all the methods I could found from here:
https://exerror.com/runtimeerror-cuda-out-of-memory-tried-to-allocate/

yet it still gave me the same error, may I know if anyone else came across a similar error and resolved it?

Many thanks for any helpful feedback.

**Comment by cathyliuchen** [comment]
Same issue and could you please upload the "pretrained_model_cora.pkl", many thanks.

**Comment by zzwjames** [comment]
The result of MVGRL cannot be reproduced, how could the author achieves a higher result than that? The code is also hard to run.

**Comment by hzhao98** [comment]
> 作者大大好， 请问能提供一下你预训练好的文件吗？ 我还想请教一下用MVGRL预训练 谢谢大大Orz

Hi, the pretrained models are provided in our code. The pretrained MVGRL model can be reproduced with utilizing the k-means algorithm and the multi-view graph contrastive loss (https://github.com/kavehhassani/mvgrl).

> Hi, I am interested in your paper “Graph Debiased Contrastive Learning with Joint Representation Clustering”. However, I have the same issue with @ZIbuyu1200 when I run your released code. Could you help us.

Hi, the pretrained models are provided in our code. The pretrained MVGRL model can be reproduced with utilizing the k-means algorithm and the multi-view graph contrastive loss (https://github.com/kavehhassani/mvgrl).

> The result of MVGRL cannot be reproduced, how could the author achieves a higher result than that? The code is also hard to run.
The pretrained results of MVGRL can absolutely be reproduced with utilizing the k-means algorithm and the multi-view graph contrastive loss (https://github.com/kavehhassani/mvgrl). And on this basis, utilizing joint clustering and debiased contrastive learning in our method can indeed enhance the performance in our code.
